language: node_js
node_js:
  - "7.10.1"
  - "8.12.0"
  - "9.11.2"
  - "10.11.0"
script: "npm run-script test-coverage"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
