language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.4"
  - "6.2"
script: "npm run-script test-coverage"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"