language: node_js
node_js:
  - "6.14.4"
  - "7.10.1"
  - "8.11.4"
  - "9.11.2"
  - "10.9.0"
script: "npm run-script test-coverage"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
